//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_Vinyl.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrdersID { get; set; }
        public int UserID { get; set; }
        public string Artist { get; set; }
        public string Album { get; set; }
        public string Format { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual User User { get; set; }
    }
}
